services:

  postgres:
    image: postgres:13.2
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    network_mode: bridge
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    entrypoint: /opt/keycloak/bin/kc.sh --config-file=/opt/keycloak/conf/keycloak.conf start-dev
    volumes:
      - ./certs/wildcard-example-com.key:/opt/keycloak/cert/wildcard-example-com.key
      - ./certs/wildcard-example-com.crt:/opt/keycloak/cert/wildcard-example-com.crt
      - ./keycloak/conf:/opt/keycloak/conf
      - keycloak_data:/opt/keycloak/data
    ports:
      - 8080:8080
      - 8443:8443
    hostname: keycloak.example.com
    network_mode: bridge
    links:
      - postgres:postgres
    depends_on:
      postgres:
        condition: service_started

  consul:
    image: hashicorp/consul:1.19.1
    container_name: consul
    volumes:
      - ./consul/conf/config.hcl:/consul/config/config.hcl
      - consul_data:/consul/data
    ports:
      - 8500:8500
    network_mode: bridge

  vault01:
    image: hashicorp/vault:1.17.3
    container_name: vault01
    command:
      - server
    environment:
      VAULT_ADDR: https://127.0.0.1:8200
      VAULT_SKIP_VERIFY: "true"
    volumes:
      - ./vault/init.sh:/vault/unseal.sh
      - ./vault/creds:/vault/creds
      - ./vault/conf/config.hcl:/vault/config/config.hcl
      - ./certs/wildcard-example-com.key:/vault/cert/wildcard-example-com.key
      - ./certs/wildcard-example-com.crt:/vault/cert/wildcard-example-com.crt
      - vault01_logs:/vault/logs
      - vault01_file:/vault/file
    cap_add:
      - IPC_LOCK
    ports:
      - 8201:8200
    hostname: vault01.example.com
    network_mode: bridge
    links:
      - consul:consul
      - keycloak:keycloak
    depends_on:
      consul:
        condition: service_started
      keycloak:
        condition: service_started

  vault02:
    image: hashicorp/vault:1.17.3
    container_name: vault02
    command:
      - server
    environment:
      VAULT_ADDR: https://127.0.0.1:8200
      VAULT_SKIP_VERIFY: "true"
    volumes:
      - ./vault/init.sh:/vault/unseal.sh
      - ./vault/creds:/vault/creds
      - ./vault/conf/config.hcl:/vault/config/config.hcl
      - ./certs/wildcard-example-com.key:/vault/cert/wildcard-example-com.key
      - ./certs/wildcard-example-com.crt:/vault/cert/wildcard-example-com.crt
      - vault02_logs:/vault/logs
      - vault02_file:/vault/file
    cap_add:
      - IPC_LOCK
    ports:
      - 8202:8200
    hostname: vault02.example.com
    network_mode: bridge
    links:
      - consul:consul
      - keycloak:keycloak
    depends_on:
      consul:
        condition: service_started
      keycloak:
        condition: service_started

  haproxy:
    image: haproxy:2.7-alpine
    container_name: haproxy
    volumes:
      - ./certs/wildcard-example-com.pem:/usr/local/etc/haproxy/wildcard-example-com.pem
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 8200:8200
    network_mode: bridge
    links:
      - vault01:vault01
      - vault02:vault02
    depends_on:
      vault01:
        condition: service_started
      vault02:
        condition: service_started

volumes:
  postgres_data:
  keycloak_data:
  consul_data:
  vault01_logs:
  vault01_file:
  vault02_logs:
  vault02_file:
